import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from "../components/ui/theme-provider"

const manrope = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Opal",
  description: "Generated by Isolu shared power ai vedio with friends",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${manrope.className} bg-[#171717]`}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {children}
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
